[package]
name = "rustiegb"
version = "0.1.0"
authors = ["Jordi Domènech <jdomenechbborges@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.116.0"
clap = "2.33.3"
gfx_device_gl = "0.16.2"
image = "0.23.12"
strum = "0.20.0"
strum_macros = "0.20.1"
readonly = "0.2.0"