[package]
name = "rustiegb"
version = "0.1.0"
authors = ["Jordi Domènech <jdomenechbborges@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.113.0"
clap = "2.33.3"
gfx_device_gl = "0.16.2"
image = "0.23.11"
strum = "0.19.5"
strum_macros = "0.19.4"