pub mod memory;
pub mod internal_ram_memory_sector;
pub mod internal_ram_8k_memory_sector;
pub mod video_ram_8k_memory_sector;
pub mod read_only_memory_sector;
pub mod timer_control;
pub mod interrupt_flag;
pub mod lcdc;
pub mod stat;
pub mod oam_memory_sector;
pub mod joypad;
pub mod wave_pattern_ram;
mod oam_entry;