name: GitHub Actions Version Updater

on:
  schedule:
    # Automatically run on every Sunday
    - cron:  '0 0 * * 0'

  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}

      - name: Run GitHub Actions Version Updater
        uses: saadmk11/github-actions-version-updater@v0.8.1
        with:
          token: ${{ secrets.WORKFLOW_SECRET }}